### PR TITLE
Update Broadcast.center to allow for options color arg

### PR DESCRIPTION
**Pull request by nelsonsbrian**

### CODE REVIEW

**Comment by nelsonsbrian** [comment]
Was getting error only passing 2 params into Broadcast.center.
image

**Review by clagiordano — COMMENTED** [review]
@nelsonsbrian thanks for your contribution, this looks good to me but the purpose of this branch is to add new types documentation and/or fix current jsDoc documentation, these proposed changes modify the current behavior of the broadcast component, making optional a required parameter, so i'm not sure if i should approve it or not.

**Comment by nelsonsbrian** [comment]
Agree with what you said. Maybe we make a sister branch with non typings, but the related fixes?

**Comment by clagiordano** [comment]
Sounds good, a new branch that starts from this one until this one is merged into 3.1 preview

**Comment by seanohue** [comment]
Yep, I suggest making a separate PR minus the typings into the main Ranvier project 👍

**Comment by nelsonsbrian** [comment]
As per discussion above

**Pull request closed without merging**
